### ISSUE TITLE
Node 21 warning

### ISSUE THREAD

**Issue by erictheswift** [oats-ts/oats-ts#142]
(node:9939) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:392:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:328:10)
    at loadBuiltinModule (node:internal/modules/helpers:101:7)
    at Module._load (node:internal/modules/cjs/loader:1001:17)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at res (./node_modules/whatwg-url/lib/url-state-machine.js:2:18)
    at Object.<anonymous> (./node_modules/whatwg-url/lib/url-state-machine.js:1297:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)

used by whatwg-url
used by cross-fetch
used by @oats-ts/fetch-client-adapter

seems bumping `cross-fetch` to 4 should remove deprecation usage:

https://github.com/jsdom/whatwg-url/issues/261

**Comment by bali182** [comment]
Updated `cross-fetch`, should be good to go with v0.0.50

**Comment by bali182** [comment]
I'll make another issue, so this doesn't get swept under the rug, but wanna do some testing before. 

Last year I tried the experimental built-in fetch, but something stopped me from switching when 18 dropped, but I can't remember what it was.

Btw if you are ever in a situation where on the client side you really NEED custom networking, you can supply a custom [ClientAdapter](https://github.com/oats-ts/oats-ts/blob/master/projects/openapi-http/index.d.ts#L4) implementation, for which I assume you are using the default [FetchClientAdapter](https://github.com/oats-ts/oats-ts/blob/master/projects/openapi-fetch-client-adapter/src/FetchClientAdapter.ts). If you can live with `cross-fetch` for now, then stick with the default, as the interfaces may change slightly over time.

**Comment by bali182** [comment]
That's pretty cool, I'll swap them out and run the tests, if all runs ok, I'll just put a minimum node version in the affected package.json, and we can be rid of the constant security vulnerabilities of the polyfills :)

**Comment by erictheswift** [comment]
Checked this out again — seems node-fetch eventually never merged whatwg-fetch version bump and using latest cross-fetch won't help, see https://github.com/lquixada/cross-fetch/issues/177

Patched like this and running on native [undici fetch](https://github.com/nodejs/undici) for a while:
```diff
diff --git a/node_modules/@oats-ts/openapi-fetch-client-adapter/lib/FetchClientAdapter.js b/node_modules/@oats-ts/openapi-fetch-client-adapter/lib/FetchClientAdapter.js
index f500106..c042f16 100644
--- a/node_modules/@oats-ts/openapi-fetch-client-adapter/lib/FetchClientAdapter.js
+++ b/node_modules/@oats-ts/openapi-fetch-client-adapter/lib/FetchClientAdapter.js
@@ -28,7 +28,6 @@ var __importDefault = (this && this.__importDefault) || function (mod) {
 Object.defineProperty(exports, "__esModule", { value: true });
 exports.FetchClientAdapter = void 0;
 const whatwg_mimetype_1 = __importDefault(require("whatwg-mimetype"));
-const crossFetch = __importStar(require("cross-fetch"));
 const try_1 = require("@oats-ts/try");
 const validators_1 = require("@oats-ts/validators");
 const openapi_parameter_serialization_1 = require("@oats-ts/openapi-parameter-serialization");
@@ -37,7 +36,7 @@ class FetchClientAdapter {
         this.config = config;
     }
     async request(request) {
-        const response = await crossFetch.fetch(request.url, this.getRequestInit(request));
+        const response = await global.fetch(request.url, this.getRequestInit(request));
         const rawHeaders = {};
         response.headers.forEach((value, key) => (rawHeaders[key.toLowerCase()] = value));
         return {
```
```diff
diff --git a/node_modules/@oats-ts/openapi-reader/lib/utils/reads/networkRead.js b/node_modules/@oats-ts/openapi-reader/lib/utils/reads/networkRead.js
index 4a1f34a..5ddf01e 100644
--- a/node_modules/@oats-ts/openapi-reader/lib/utils/reads/networkRead.js
+++ b/node_modules/@oats-ts/openapi-reader/lib/utils/reads/networkRead.js
@@ -6,7 +6,6 @@ Object.defineProperty(exports, "__esModule", { value: true });
 exports.networkRead = void 0;
 const try_1 = require("@oats-ts/try");
 const urijs_1 = __importDefault(require("urijs"));
-const cross_fetch_1 = require("cross-fetch");
 const networkRead = (expectedScheme) => async (uri) => {
     const scheme = new urijs_1.default(uri).scheme();
     if (scheme !== expectedScheme) {
@@ -17,7 +16,7 @@ const networkRead = (expectedScheme) => async (uri) => {
         });
     }
     try {
-        const response = await (0, cross_fetch_1.fetch)(uri);
+        const response = await (0, global.fetch)(uri);
         const text = await response.text();
         return (0, try_1.success)(text);
     }
```
